// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"boilerplate/internal/app/router"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, error) {
	routerRouter := &router.Router{}
	engine := InitGinEngine(routerRouter)
	injector := &Injector{
		Engine: engine,
	}
	return injector, nil
}
