// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

// Injectors from wire.go:

func BuildInjector() (*Injector, error) {
	engine := InitGinEngine()
	injector := &Injector{
		Engine: engine,
	}
	return injector, nil
}
