# 啟動時是否印出配置參數
PrintConfig = true

# debug:開發,test:測試,release:正式
RunMode = "debug"

[HTTP]
# http listening address
Host = "0.0.0.0"
# http listening port
Port = 10088
# 證書路經
CertFile = ""
# 證書密鑰
KeyFile = ""
# http優雅關閉等待超時時長(單位秒)
ShutdownTimeout = 30
# 允許的最大内容長度(64M)
MaxContentLength = 67108864
# 允許輸出的最大請求日誌長度
MaxReqLoggerLength = 1024
# maximum duration for reading the entire request, including the body (單位:sec)
ReadTimeout = 10
# the maximum duration before timing out writes of the response. (單位:sec)
WriteTimeout = 30
# the maximum amount of time to wait for the next request when keep-alives are enabled. (單位:sec)
IdleTimeout = 30

[CORS]
# 是否啟用
Enable = true
# 允許跨域請求的域名列表(*表示全部允許)
AllowOrigins = ["*"]
# 允許跨域請求的請求方式列表
AllowMethods = ["GET", "POST", "PUT", "DELETE", "PATCH"]
# 允許客戶端与跨域請求一起使用的非簡單標頭的列表
AllowHeaders = ["content-type", "authorization"]
# 請求是否可以包含cookie，HTTP身份驗證或客戶端SSL證書等用戶憑據
AllowCredentials = true
# 可以缓存预检請求结果的時間（以秒為單位）
MaxAge = 7200
