# 啟動時是否印出配置參數
PrintConfig = true

# debug:開發,test:測試,release:正式
RunMode = "debug"

[HTTP]
# http listening address
Host = "0.0.0.0"
# http listening port
Port = 10088
# 證書路經
CertFile = ""
# 證書密鑰
KeyFile = ""
# http優雅關閉等待超時時長(單位秒)
ShutdownTimeout = 30
# 允許的最大内容長度(64M)
MaxContentLength = 67108864
# 允許輸出的最大請求日誌長度
MaxReqLoggerLength = 1024
# maximum duration for reading the entire request, including the body (單位:sec)
ReadTimeout = 10
# the maximum duration before timing out writes of the response. (單位:sec)
WriteTimeout = 30
# the maximum amount of time to wait for the next request when keep-alives are enabled. (單位:sec)
IdleTimeout = 30

[CORS]
# 是否啟用
Enable = true
# 允許跨域請求的域名列表(*表示全部允許)
AllowOrigins = ["*"]
# 允許跨域請求的請求方式列表
AllowMethods = ["GET", "POST", "PUT", "DELETE", "PATCH"]
# 允許客戶端与跨域請求一起使用的非簡單標頭的列表
AllowHeaders = ["content-type", "authorization"]
# 請求是否可以包含cookie，HTTP身份驗證或客戶端SSL證書等用戶憑據
AllowCredentials = true
# 可以缓存预检請求结果的時間（以秒為單位）
MaxAge = 7200

[GZIP]
# 是否啟用
Enable = false
# 排除的文件擴展名
ExcludedExtentions = [".png", ".gif", ".jpeg", ".jpg"]
# 排除的請求路經
ExcludedPaths = []

[Log]
# 日誌级别(1:fatal 2:error,3:warn,4:info,5:debug,6:trace)
Level = 5
# 日誌格式（支持輸出格式：text/json）
Format = "text"
# 日誌輸出(支持：stdout/stderr/file)
Output = "stdout"
# 指定日誌輸出的文件路經
OutputFile = "data/output.log"
# 日誌輪詢數量
RotationCount = 20
# 日誌輪詢時間周期
RotationTime = 24

[Gorm]
# 是否開啟调試模式
Debug = true
# 數據庫類型(目前支持的數據庫類型：mysql/sqlite3/postgres)
DBType = "sqlite3"
# 設置連接可以重用的最長時間(單位：秒)
MaxLifetime = 7200
# 設置數據庫的最大打開連接數
MaxOpenConns = 150
# 設置空閒連接池中的最大連接數
MaxIdleConns = 50
# 數據庫表名前缀
TablePrefix = ""
# 是否啟用自動映射數據庫表結構
EnableAutoMigrate = true

[MySQL]
# 連接地址
Host = "127.0.0.1"
# 連接端口
Port = 3306
# 用戶名
User = "root"
# 密碼
Password = "123456"
# 數據庫
DBName = "mysql_db"
# 連接参數menu
Parameters = "charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"

[Postgres]
# 連接地址
Host = "0.0.0.0"
# 連接端口
Port = 5432
# 用戶名
User = "user"
# 密碼
Password = "password"
# 數據庫
DBName = "postgresql"
# SSL模式
SSLMode = "disable"

[Sqlite3]
# 數據庫路經
Path = "data/sqlite3.db"
